name: Python Ruff Lint and Format CI

on:
  push:
    paths: ["**/*.py", "**/*.pyi", "**/*.ipynb", "**/pyproject.toml"]
    branches: [main]
  pull_request:
    paths: ["**/*.py", "**/*.pyi", "**/*.ipynb", "**/pyproject.toml"]
    branches: [main]
  workflow_dispatch:

jobs:
  ruff-lint-and-format:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Run Ruff Linter with auto-fix
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "check --fix --show-fixes"

      - name: Run Ruff Formatter with auto-fix
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "format"

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        id: auto-commit-action # mandatory for the output to show up in ${{ steps }}
        with:
          commit_message: "chore: auto-fixed by Ruff linter and formatter"

      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"

      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"
