name: Python Code Quality CI

on:
  push:
    paths: ["**/*.py", "**/*.pyi", "**/*.ipynb", "**/pyproject.toml"]
    branches: [main]
  pull_request:
    paths: ["**/*.py", "**/*.pyi", "**/*.ipynb", "**/pyproject.toml"]
    branches: [main]
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Run Ruff Linter
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "check"
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Run Ruff Formatter
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "format --check"
  type-consistency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
      - name: Sync UV Dependencies
        run: uv sync

      - name: Add Virtual Environment to PATH
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Run Pyright Type Checker
        uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
